# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.markdown_transformer:
    class: AppBundle\Service\MarkdownTransformer
    arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']

  app.markdown_extension:
    class: AppBundle\Twig\MarkdownExtension
    autowire: true
    #arguments: ['@app.markdown_transformer']
    tags:
      - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
